### ISSUE TITLE
Video-Liste Sortieren

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#227]
Es wird gewünscht, dass dozenten die Videoliste selbst sortieren können.

**Comment by rrolf** [comment]
Ich würde vielleicht für den anfang damit beginnen, dass man die Sortierkriterien aus search nutzt und die Lehrenden auswählen lässt, welche Sortierung man nutzt? 

Ein Lehrenden schrieb, dass er die Aufzeichnungen so benennt, wie sie angeschaut werden sollten:
Kapitel 1, Kapitel 2 (wenn dass denn noch 01 und 02 wäre, könnte man das gut nutzen) und der Rest endpoint kennt ja schon:

sort: The sort order. May include any of the following: DATE_CREATED, DATE_PUBLISHED, TITLE, SERIES_ID, MEDIA_PACKAGE_ID, CREATOR, CONTRIBUTOR, LANGUAGE, LICENSE, SUBJECT, DESCRIPTION, PUBLISHER. Add '_DESC' to reverse the sort order (e.g. TITLE_DESC).

**Comment by tgloeggl** [comment]
Studierende können die Sortierung selbst auch ändern (für die Sessionlaufzeit)

**Comment by felix-itz** [comment]
Looks like the search functionality had been removed: https://github.com/elan-ev/studip-opencast-plugin/commit/b4be3a6f5d618d8d07249f159121b077ea391350#diff-f3671bf120fbe89c1a1eb7dd2570c762L15

**Comment by tgloeggl** [comment]
> Looks like the search functionality had been removed: [b4be3a6#diff-f3671bf120fbe89c1a1eb7dd2570c762L15](https://github.com/elan-ev/studip-opencast-plugin/commit/b4be3a6f5d618d8d07249f159121b077ea391350#diff-f3671bf120fbe89c1a1eb7dd2570c762L15)

Yes, the search functionality was broken and there was no time to fix it, so it has been removed for the time beeing.
This doesn't matter for this ticket, though, because the sort order will be passed to the oc-search-endpoint.

- [ ] Auf der Oberfläche eine Liste von Sortiermöglichkeiten anbieten, die der Lehrende einstellen und speichern kann
- [ ] Studierende erhalten standardmäßig die vom Lehrenden eingestellte Sortierung, können diese aber für die aktuelle Sessions pro Veranstaltung anpassen
- [ ] Standardmäßig soll nach DATE_CREATED_DESC sortiert werden

**Comment by tgloeggl** [comment]
fixed in 8a9edc69c9d718d877db0b17ddb61a09519928e0
