### ISSUE TITLE
SQL exception when adding multiple servers

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#718]
Adding multiple servers, Stud.IP complains about SQL constraint violations. The input should be checked to present a violation like this. Even worse, the error message contains the opencast password which is printed in plain text to the screen and maybe even appears in the logs?

![Screenshot from 2023-06-01 11-01-26](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/15d5bec9-028b-4473-ba0c-151f510d7438)

*(luckily, here you only get the first few characters of a very long password)*

**Comment by tgloeggl** [comment]
The problem arises when adding the same server with the same credentials. This should be prevented client-side in the plugin and the error message should of course not show the password.
The password is shown because MySQL reports the primary key in conflict which the password is part of. Multiple things need to be done here:
- [ ] The primary key should only be the server URI. The credentials should not be part of the SQL-Key.
- [ ] Trying to add another server with the same server URI is forbidden, should be checked an reported back to the user.
